# Generated by Django 4.2.7 on 2023-11-20 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StoreItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=500)),
                ('origin', models.CharField(max_length=20)),
                ('brand', models.CharField(max_length=20)),
                ('category', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('discount', models.PositiveIntegerField()),
                ('amount_sold', models.PositiveIntegerField()),
            ],
        ),
    ]
